version: '3.8'
services:

  database:
    image: postgres:14.1-alpine
    container_name: task-service-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - task-service-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-service-network
      
  task-service:
    build: ./task-tracker-service/
    container_name: task-service
    restart: always
    environment:
      - PORT=${TASK_SERVICE_CONTAINER_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_SECRET=${ACCESS_SECRET}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${TASK_SERVICE_HOST_PORT}:${TASK_SERVICE_CONTAINER_PORT}
    networks:
      - task-service-network

  auth-service:
    build: ./auth-service/
    container_name: auth-service
    restart: always
    environment:
      - PORT=${AUTH_SERVICE_CONTAINER_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - ACCESS_SECRET_EXPIRE=${ACCESS_SECRET_EXPIRE}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - REFRESH_SECRET_EXPIRE=${REFRESH_SECRET_EXPIRE}
    depends_on:
      database:
        condition: service_healthy
      task-service:
        condition: service_started
    ports:
      - ${AUTH_SERVICE_HOST_PORT}:${AUTH_SERVICE_CONTAINER_PORT}
    networks:
      - task-service-network

  admin-service:
    build: ./admin-service/
    container_name: admin-service
    restart: always
    environment:
      - PORT=${ADMIN_SERVICE_CONTAINER_PORT}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_SECRET=${ACCESS_SECRET}
    depends_on:
      database:
        condition: service_healthy
      task-service:
        condition: service_started
    ports:
      - ${ADMIN_SERVICE_HOST_PORT}:${ADMIN_SERVICE_CONTAINER_PORT}
    networks:
      - task-service-network

volumes:
  task-service-db:
  
networks:
  task-service-network: