version: '3.8'
services:

  database:
    image: postgres:14.1-alpine
    container_name: task-service-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_HOST_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - task-service-db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task-service-network
      
  backend:
    build: .
    container_name: task-service-backend
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}
    networks:
      - task-service-network

volumes:
  task-service-db:
  
networks:
  task-service-network: