version: '3.8'
services:

  task-service:
    image: ${IMAGE_NAME_WITH_TAG}
    container_name: ${APP_NAME}
    restart: always
    environment:
      - PORT=${TASK_SERVICE_CONTAINER_PORT}
      - DB_URL=${DB_URL}
      - DB_CONTAINER_PORT=${DB_CONTAINER_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_CONTAINER_PORT=${REDIS_CONTAINER_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CACHE_TIME=${CACHE_TIME}
    ports:
      - ${TASK_SERVICE_HOST_PORT}:${TASK_SERVICE_CONTAINER_PORT}
    networks:
      - task-tracker-network
  
networks:
  task-tracker-network:
    external: true