server:
  port: 8098
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowed-headers:
              - "*"
            allowedOrigins:
              - "http://localhost:3005"
            allowedMethods:
              - "*"
#          add-to-simple-url-handler-mapping: true
      routes:
        - id: auth-service
          uri: http://localhost:8097
          predicates:
            - Path=/v1/auth/**
        - id: task-service
          uri: http://localhost:8099
          predicates:
            - Path=/v1/admin/**,/v1/tasks/**,/v1/users/**