version: '3.8'
services:

  task-service:
    image: ${IMAGE_NAME_WITH_TAG}
    container_name: ${APP_NAME}
    restart: always
    environment:
      - PORT=${GATEWAY_SERVICE_CONTAINER_PORT}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_CONTAINER_PORT}
      - TASK_SERVICE_PORT=${TASK_SERVICE_CONTAINER_PORT}
    ports:
      - ${GATEWAY_SERVICE_HOST_PORT}:${GATEWAY_SERVICE_CONTAINER_PORT}
    networks:
      - task-tracker-network
  
networks:
  task-tracker-network:
    external: true